config/routes.rb
Rails.application.routes.draw do

  resources :feeds
  resources :blogs do
    collection do
      post :confirm
    end
  end
  
   resources :users, only: [:new, :create, :show]
   resources :sessions, only: [:new, :create, :destroy]
   resources :users
   resources :blogs, only: [:new, :edit, :show]
   resources :favorites, only: [:create, :destroy]
   
   if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user,optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, :content, presence: true
  validates :content, length: { in: 1..140 }
  
  mount_uploader :image,ImageUploader
  
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  
  mount_uploader :icon,ImageUploader
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
    before_action :set_blog, only: [:show, :edit, :update, :destroy ]
    before_action :login_confirm, only: [:show, :edit, :new ,:update ,:destroy]
  
    def index
      @blogs = Blog.all
    end
    
    def new
      if params[:back]
        @blog = Blog.new(blog_params)
      else
        @blog = Blog.new
      end
    end
    

   def confirm
     @blog = Blog.new(blog_params)
     render :new if @blog.invalid?
   end

   def create
     @blog = Blog.new(blog_params)
     @blog.user_id = current_user.id
     @blog.image.retrieve_from_cache! params[:cache][:image]
     @blog.save!
     if @blog.save
       redirect_to blogs_path, notice: "ブログを作成しました！"
       BlogMailer.blog_mail(@blog).deliver
     else
       render 'new'
     end
   end

 
   def edit
      
   end
  
   def update
       #@blog = Blog.find(params[:id])
     if @blog.update(blog_params)
       redirect_to blogs_path, notice: "ブログを編集しました！"
     else
       render 'edit'
     end
   end

   def show
     @favorite = current_user.favorites.find_by(blog_id: @blog.id)
     #@blog = Blog.find(params[:id])
   end

   def destroy
     @blog.destroy
     redirect_to blogs_path, notice:"ブログを削除しました！"
   end
   

  
   private
      def blog_params
       params.require(:blog).permit(:title, :content, :image)
      end
  
      # idをキーとして値を取得するメソッド
      def set_blog
       @blog = Blog.find(params[:id])
      end
      
      def login_confirm
          redirect_to new_session_path unless !current_user.nil?
      end
      
         
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to new_session_path
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
  
  private
      
      
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @favorites_blogs = @user.favorite_blogs
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
   end
   
   def logged_in?
    !current_user.nil?
   end
   
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<html>
<body>

   <%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
   <% if @blog.errors.any? %>
    <div id="error_explanation">
        <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
            <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
<div class="container">
 <div class="row">
    <%= form.label :title %>
    <%= form.text_field :title %>
    
    <%= form.label :content %>
    <%= form.text_field :content %>


    <%= form.label :image %>
    <center><%= form.file_field :image, id: :blog_image %></center>
    <%= form.hidden_field :image_cache %>
  
 <br><%= form.submit %>
  
  
<% end %>

<br>
<br><%= link_to '一覧に戻る',blogs_path %>

</div>
</div>


</body>
</html>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <div class="container">
  <div class="row">
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <% unless @blog.image.blank? %>
      <%= image_tag(@blog.image.url,:size => "250x250") %>
      <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <% end %>
  <p></p>
  <p><%= form.submit "登録する"%></p>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field :"cache[image]",@blog.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

</div>
</div>

app/views/blogs/edit.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blogs/index.html.erb
<html>
<body>
  <section class="main-header">
    <%= image_tag('top.jpg') %>
  </section>
<br></br>
<h3><%= link_to '新しく画像を投稿する', new_blog_path %></h3>

<div class="container">
  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="col-xs-12 col-md-12 blog-panel">
         <h2><%="User:" %><%= blog.user.name %></h2>
         <p><%= image_tag(blog.image_url,:size => "250x250") unless blog.image.blank? %></p>
         <p><%="Comment:" %><%= blog.content %></p>
        <div class="blog-links">
          <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
          <li><%= link_to 'Show', blog, class: 'btn btn-default' %></li>
          <%  if blog.user_id == current_user.id %>
             <li><%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %></li>
             <li><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></li>
           <% else %>

           <% end %>
           </ul>
        </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>
  
  </body>
</html>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
 <div class="container">
 <div class="row">
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>画像:</p>
<p><%= image_tag(@blog.image_url,:size => "250x250") unless @blog.image.blank? %></p>

<% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
  </div>
  </div>
  
  

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image, id: :feed_image %>
  <%= form.hidden_field :image_cache %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><% pluralize(@user.errors.count,"error") %>エラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


 <div class="container">
 <div class="row">
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.label :icon %>
  <center><%= f.file_field :icon,id: :user_icon %></center>
  <%= f.hidden_field :icon_cache %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

   <br>
  <br><%= f.submit "Create my account" %>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<html>
<body>

<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<p><p>画像:</p>
<p><strong>Icon:</strong></p>
<p><%= image_tag @user.icon %></p>

<div class="container">
  <div class="row">
    <% @favorites_blogs.each do |favorites_blog| %>
      <div class="col-xs-12 col-md-12 blog-panel">
         <h2><%="User:" %><%= favorites_blog.user.name %></h2>
         <p><%= image_tag(favorites_blog.image_url,:size => "250x250") unless favorites_blog.image.blank? %></p>
         <p><%="Comment:" %><%= favorites_blog.content %></p>
        <div class="blog-links">
          <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
          <li><%= link_to 'Show', favorites_blog, class: 'btn btn-default' %></li>
          <%  if favorites_blog.user_id == current_user.id %>
             <li><%= link_to 'Edit', edit_blog_path(favorites_blog), class: 'btn btn-info' %></li>
             <li><%= link_to 'Destroy', favorites_blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></li>
           <% else %>

           <% end %>
           </ul>
        </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>
  

  </body>
</html>